apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: grafana
    helm:
      values: |
        adminUser: "admin"
        adminPassword: "password"
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.13.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true